var ROUTER_CHANGE=Symbol("ROUTER_CHANGE"),APP_DATAFLOW_CHANGE=Symbol("APP_DATAFLOW_CHANGE"),DATAFLOW_CHANGE=Symbol("DATAFLOW_CHANGE");export{ROUTER_CHANGE,APP_DATAFLOW_CHANGE,DATAFLOW_CHANGE};
//# sourceMappingURL=actions.js.map
